baseURL = "https://mouret.pro/"
languageCode = "fr"
title = "Mouret.pro"
theme = "isebmo-tfada"
SectionPagesMenu = "main"
googleAnalytics = ""
description = "Site perso sur le dÃ©v, les bonnes pratiques ğŸ‘, les outils, la productivitÃ© ğŸ‘©â€ğŸ’». Le site qui va rien changer Ã  ta vie mais peut t'aider ğŸ˜‚"
preserveTaxonomyNames = true
disqusShortname = "mouretpro"
[permalinks]
  post = "/:title/"

[params]
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/sebmouret"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6
  body_classes = "font"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Mes outils ğŸ› "
    url = "/tools/"
    weight = 0

  [[menu.main]]
    identifier = "post"
    name = "Articles ğŸ“š"
    post = "<span class='alert'>New!</span>"
    url = "/post/"
    weight = 1
